---
version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - ./monitoring/secrets/:/opt/prometheus/secrets/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - backend
    depends_on:
      - app-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      - backend
    depends_on:
      - prometheus

  app:
    image: nginx
    container_name: app
    volumes:
     - ./app/templates:/etc/nginx/templates
     - ./app/data1:/data1
    ports:
      - 80:80
      - 8080:8080
    networks:
      - backend


  app-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: app-exporter
    user: root
    volumes:
     - ./app/nodeexporter:/etc/nodeexporter
    environment:
      - SCRAPE_URI=http://app:8080/stub_status
      - SSL_CA_CERT=/etc/nodeexporter/myCA.pem
      - SSL_CLIENT_CERT=/etc/nodeexporter/Client.crt
      - SSL_CLIENT_KEY=/etc/nodeexporter/Client_nopass.key
      - SSL_VERIFY=true
    restart: always
    ports:
      - 9113:9113
    networks:
      - backend
    depends_on:
      - app

networks:
  backend:
    driver: bridge
