global:
receivers:
- name: gmail-notifications
  email_configs:
  - to: email@email.com
    from: email@email.com
    smarthost: host
    auth_username: email@email.com
    auth_identity: email@email.com
    auth_password: password
    send_resolved: true
- name: default

route:
  receiver: 'default'
  routes:
  - receiver: 'gmail-notifications'
    match:
      alertname: QuietHours
