global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    static_configs:
      - targets: ['192.168.0.92:9113']
rule_files:
 - rules.yml

alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093
