global:
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx'
    tls_config:
      ca_file: /opt/prometheus/secrets/myCA.pem
      cert_file: /opt/prometheus/secrets/prom_server.crt
      key_file: /opt/prometheus/secrets/prom_server_nopass.key
      server_name: app-exporter
      insecure_skip_verify: true
    scheme: https
    static_configs:
      - targets: ['app-exporter:9113']
  - job_name: 'node'
    scheme: https
    tls_config:
      ca_file: /opt/prometheus/secrets/myCA.pem
      insecure_skip_verify: true
    static_configs:
      - targets: ['node-exporter:9100']
rule_files:
 - rules.yml

alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093
