groups:
- name: QuietHours
  rules:
  - alert: QuietHours
   # Condition for alerting
    expr: hour() <= 22 and up == 0 or hour() >= 8 and up == 0
    for: 1m
     # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
     # Labels - additional labels to be attached to the alert
    labels:
      alertname: QuietHours
